baseURL = 'https://www.scheid.tech/'
languageCode = 'de'
title = 'scheid.tech'
author = 'Christian Scheid'
theme = 'risotto'
defaultContentLanguage = 'de'
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
timeZone = 'Europe/Berlin'

[languages]
  [languages.de]
    contentDir = 'content/de'
    disabled = false
    languageCode = 'de-DE'
    languageDirection = 'ltr'
    languageName = 'Deutsch'
    title = 'scheid.tech'
    weight = 1
    [languages.de.params]
      subtitle = ''
    [languages.de.menus]
      [[languages.de.menus.main]]
        identifier = "blog"
        name = "Blog"
        url = "/"
        weight = 1
      [[languages.de.menus.main]]
        identifier = "impressum"
        name = "Impressum"
        url = "/impressum/"
        weight = 20
      [[languages.de.menus.main]]
        identifier = "disclaimer"
        name = "Disclaimer"
        url = "/disclaimer/"
        weight = 30
      [[languages.de.menus.main]]
        identifier = "datenschutzerklaerung"
        name = "Datenschutzerkl√§rung"
        url = "/datenschutzerklaerung/"
        weight = 40

  [languages.en]
    contentDir = 'content/en'   
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'scheid.tech'
    weight = 2
    [languages.en.params]
      subtitle = ''
    [languages.en.menus]
      [[languages.en.menus.main]]
        identifier = "blog"
        name = "Blog"
        url = "/"
        weight = 1
      [[languages.en.menus.main]]
        identifier = "imprint"
        name = "imprint"
        url = "/imprint/"
        weight = 20
      [[languages.en.menus.main]]
        identifier = "disclaimer"
        name = "Disclaimer"
        url = "/disclaimer/"
        weight = 30
      [[languages.en.menus.main]]
        identifier = "privacy-policy"
        name = "Privacy policy"
        url = "/privacy-policy/"
        weight = 40

[params.theme]
palette = "solarized-dark"